define('webview/nls/webview_th',{
'webview/resources/slreportgen_webview/nls/modelviewer':{"OpenInNewTab":"Open In New Tab","Open":"Open","NoExport":"This system was not exported.","ModelBrowserButtonLabel":"Hide/Show Model Browser","searchResults":"Search Results:","propertyName":"Property Name","ExplorerBarButtonLabel":"Hide/Show Explorer Bar","advancedSearch":"Advanced Search","ViewAll":"View All","parent":"Parent","name":"Name","searchCurrentAndBelow":"Search current and below...","propertyValue":"Property Value","FitToViewButtonLabel":"Fit to View","maskType":"Mask Type","MarqueeZoomButtonLabel":"Zoom","blockType":"Block Type","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelbrowser':{"OpenInNewTab":"Open In New Tab","Open":"Open","Title":"Model Browser","_localized":{}}
,
'dijit/nls/common':{"buttonOk":"ตกลง","buttonCancel":"ยกเลิก","buttonSave":"บันทึก","itemClose":"ปิด","_localized":{}}
,
'dijit/nls/loading':{"loadingState":"กำลังโหลด...","errorState":"ขออภัย เกิดข้อผิดพลาด","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelinspector':{"CodeGeneration":"Code Generation","ParameterAttributes":"Parameter Attributes","Documentation":"Documentation","LoggingAndAccessibility":"Logging and Accessibility","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/utils':{"ChromeLocalFileSupport":"<p>Simulink Web View cannot be viewed in Google Chrome because of local file security restrictions. To allow local file access, try the following:</p> <h4>Microsoft Windows</h4> <ol> <li>Click the <b>Start</b> button and search for the browser executable,  such as \"Chrome\".</li> <li>Right-click and drag the matched browser search result to an open area. Select <b>Create shortcuts here</b>.</li> <li>Right-click the newly created shortcut and select <b>Properties</b>.</li> <li>Click the <b>Shortcut</b> tab.</li> <li>In the target edit box, append \"--allow-file-access-from-files\", with no quotes.</li> <li>Click <b>OK</b> to dismiss property dialog box.</li> <li>Verify that the browser is no longer running.</li> <li>Double-click on the newly created shortcut to start the browser.</li> </ol> <h4>Mac</h4> <ol> <li>Run Terminal.app.</li> <li>Type \"open /Applications Google Chrome.app --allow-file-access-from-files\", with no quotes.</li> </ol> <h4>Linux</h4> <ol> <li>Start terminal.</li> <li>Type \"./chromium-browser --allow-file-access-from-files\", with no quotes.</li> </ol>","UnsupportedBrowser":"Unsupported Browser","SvgSupport":"<h4>SVG Support Required</h4> <p>Your browser does not support Scalable Vector Graphics.  Try to use one of the following browser: <ul> <li><a href=\"http://www.google.com/chrome/\">Chrome</a></li> <li><a href=\"http://www.mozilla.org/products/firefox/all\">Firefox</a></li> <li><a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">Internet Explorer 9 or later</a></li> </ul>","_localized":{}}
});