define('webview/nls/webview_ja-jp',{
'webview/resources/slreportgen_webview/nls/modelviewer':{"OpenInNewTab":"新しいタブで開く","Open":"開く","NoExport":"このシステムはエクスポートされませんでした。","ModelBrowserButtonLabel":"モデル ブラウザーの非表示/表示","searchResults":"検索結果:","propertyName":"プロパティ名","ExplorerBarButtonLabel":"エクスプローラー バーの非表示/表示","advancedSearch":"詳細検索","ViewAll":"すべて表示","parent":"親","name":"名前","searchCurrentAndBelow":"現在の階層以下を検索...","propertyValue":"プロパティ値","FitToViewButtonLabel":"ビューに合わせる","maskType":"マスク タイプ","MarqueeZoomButtonLabel":"ズーム","blockType":"ブロック タイプ","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelbrowser':{"OpenInNewTab":"新しいタブで開く","Open":"開く","Title":"モデル ブラウザー","_localized":{}}
,
'dijit/nls/common':{"buttonOk":"OK","buttonCancel":"キャンセル","buttonSave":"保存","itemClose":"閉じる","_localized":{}}
,
'dijit/nls/loading':{"loadingState":"ロード中...","errorState":"エラーが発生しました。","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/modelinspector':{"CodeGeneration":"コード生成","ParameterAttributes":"パラメーター属性","Documentation":"ドキュメンテーション","LoggingAndAccessibility":"ログとユーザー補助機能","_localized":{}}
,
'webview/resources/slreportgen_webview/nls/utils':{"ChromeLocalFileSupport":"<p>Simulink の Web ビューは、ローカル ファイルのセキュリティ制限のため Google Chrome では表示できません。ローカル ファイルへのアクセスを可能にするには、以下を試してください。</p> <h4>Microsoft Windows</h4> <ol> <li><b>[スタート]</b> ボタンをクリックして、\"Chrome\" などのブラウザーの実行可能ファイルを検索します。</li> <li>一致したブラウザー検索結果を右クリックして空白の領域にドラッグします。<b>[ショートカットをここに作成]</b> を選択します。</li> <li>新しく作成されたショートカットを右クリックして <b>[プロパティ]</b> を選択します。</li> <li><b>[ショートカット]</b> タブをクリックします。</li> <li>ターゲットのエディット ボックスで、\"--allow-file-access-from-files\" を引用符なしで追加します。</li> <li><b>[OK]</b> をクリックしてプロパティ ダイアログ ボックスを閉じます。</li> <li>ブラウザーが実行されていないことを確認します。</li> <li>新しく作成されたショートカットをダブルクリックしてブラウザーを起動します。</li> </ol> <h4>Mac</h4> <ol> <li>Terminal.app を実行します。</li> <li>\"open /Applications Google Chrome.app --allow-file-access-from-files\" を引用符なしで入力します。</li> </ol> <h4>Linux</h4> <ol> <li>ターミナルを起動します。</li> <li>\"./chromium-browser --allow-file-access-from-files\" を引用符なしで入力します。</li> </ol>","UnsupportedBrowser":"サポートされていないブラウザー","SvgSupport":"<h4>SVG サポートが必要</h4> <p>ブラウザーが Scalable Vector Graphics をサポートしていません。次のいずれかのブラウザーを使用してみてください。 <ul> <li><a href=\"http://www.google.com/chrome/\">Chrome</a></li> <li><a href=\"http://www.mozilla.org/products/firefox/all\">Firefox</a></li> <li><a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">Internet Explorer 9 以降</a></li> </ul>","_localized":{}}
});